CC = gcc -Wall

compile:
	$(CC) -o main main.c

clean:
	rm main

run:
	./main . ">" 01.01.2019
	./main . "=" 20.03.2019
	./main . "<" 22.03.2019
	./main . ">" 10.10.2020
	./main . "<" 01.01.2019
	./main . "=" 22.03.2019
